name       : perl-cairo
version    : '1.109'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Cairo-1.109.tar.gz : 8219736e401c2311da5f515775de43fd87e6384b504da36a192f2b217643077f
homepage   : https://metacpan.org/pod/Cairo
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Perl wrappers for Cairo
description: |
    Cairo provides Perl bindings for the vector graphics library cairo. It supports multiple output targets, including PNG, PDF and SVG. Cairo produces identical output on all those targets.
builddeps  :
    - pkgconfig(cairo)
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
