name       : perl-cairo
version    : 1.106
release    : 1
source     :
    - https://netcologne.dl.sourceforge.net/project/gtk2-perl/Cairo/1.106/Cairo-1.106.tar.gz : e64803018bc7cba49e73e258547f5378cc4249797beafec524852140f49c45c4
license    : LGPL-2.1
component  : programming.perl
summary    : Perl wrappers for Cairo
description: |
    Perl wrappers for Cairo
builddeps  :
    - pkgconfig(cairo)
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
