name       : perl-cairo
version    : '1.107'
release    : 5
source     :
    - https://netcologne.dl.sourceforge.net/project/gtk2-perl/Cairo/1.107/Cairo-1.107.tar.gz : 5e1de126ddf93bd5b13f13a52f50d7f7af1157265b7f10e53d585ee1827be169
license    : LGPL-2.1
component  : programming.perl
summary    : Perl wrappers for Cairo
description: |
    Perl wrappers for Cairo
builddeps  :
    - pkgconfig(cairo)
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
